# Generated by Django 4.2.7 on 2023-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('', 'default'), ('trending', 'trending'), ('most played', 'most played'), ('featured', 'featured')], max_length=50),
        ),
    ]
