# Generated by Django 4.2.7 on 2023-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_slug_alter_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default=models.CharField(max_length=200), max_length=50),
        ),
    ]
